"""add_rubro_field_to_tienda

Revision ID: 849d2968c4fe
Revises: 
Create Date: 2025-11-20 10:17:17.500357

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '849d2968c4fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiendas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rubro', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiendas_id'), 'tiendas', ['id'], unique=False)
    op.create_index(op.f('ix_tiendas_is_active'), 'tiendas', ['is_active'], unique=False)
    op.create_index(op.f('ix_tiendas_nombre'), 'tiendas', ['nombre'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('mensaje', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nivel_urgencia', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_created_at'), 'insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_index(op.f('ix_insights_is_active'), 'insights', ['is_active'], unique=False)
    op.create_index(op.f('ix_insights_nivel_urgencia'), 'insights', ['nivel_urgencia'], unique=False)
    op.create_index(op.f('ix_insights_tienda_id'), 'insights', ['tienda_id'], unique=False)
    op.create_index(op.f('ix_insights_tipo'), 'insights', ['tipo'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('precio_costo', sa.Float(), nullable=False),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_is_active'), 'productos', ['is_active'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=False)
    op.create_index(op.f('ix_productos_tienda_id'), 'productos', ['tienda_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_tienda_id'), 'users', ['tienda_id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_pago', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('payment_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('afip_cae', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('afip_cae_vto', sa.DateTime(), nullable=True),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_fecha'), 'ventas', ['fecha'], unique=False)
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    op.create_index(op.f('ix_ventas_payment_id'), 'ventas', ['payment_id'], unique=False)
    op.create_index(op.f('ix_ventas_status_pago'), 'ventas', ['status_pago'], unique=False)
    op.create_index(op.f('ix_ventas_tienda_id'), 'ventas', ['tienda_id'], unique=False)
    op.create_table('detalles_venta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('venta_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_venta_id'), 'detalles_venta', ['id'], unique=False)
    op.create_index(op.f('ix_detalles_venta_producto_id'), 'detalles_venta', ['producto_id'], unique=False)
    op.create_index(op.f('ix_detalles_venta_venta_id'), 'detalles_venta', ['venta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_venta_venta_id'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_producto_id'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_id'), table_name='detalles_venta')
    op.drop_table('detalles_venta')
    op.drop_index(op.f('ix_ventas_tienda_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_status_pago'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_payment_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_fecha'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_users_tienda_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_productos_tienda_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_is_active'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_insights_tipo'), table_name='insights')
    op.drop_index(op.f('ix_insights_tienda_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_nivel_urgencia'), table_name='insights')
    op.drop_index(op.f('ix_insights_is_active'), table_name='insights')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_created_at'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_tiendas_nombre'), table_name='tiendas')
    op.drop_index(op.f('ix_tiendas_is_active'), table_name='tiendas')
    op.drop_index(op.f('ix_tiendas_id'), table_name='tiendas')
    op.drop_table('tiendas')
    # ### end Alembic commands ###
